title: Alexander Denker
author:
  name: Alexander Denker
#  email: a.denker@uni-bremen.de
description: > # this means to ignore newlines until "show_excerpts:"
  I am a post doctoral researcher at the University College London and are interesting in applications of deep learning for inverse problems.
  
show_excerpts: false # set to true to show excerpts on the homepage

#domain: alexanderdenker.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#url: https://alexanderdenker.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: DenkerAlexander
    github:  alexdenker
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - publications.md
 - about.md


show_excerpts: true

# Build settings
theme: minima
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
